### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by sm2017** [DavidOberholzer/SwaggerReactAdminGenerator#5]
I run generator in windows 10 , Python 2.7.15

error is

```
File "generator.py", line 126
def render_to_string(filename: str, context: dict): 
                             ^                                              
SyntaxError: invalid syntax
--
```

**Comment by cobusc** [comment]
Hi @sm2017 . You get that error because you are using Python 2.7. The code requires Python 3.

**Comment by sm2017** [comment]
@cobusc I'm not familiar with python , what about `ModuleNotFoundError: No module named 'click'`

**Comment by sm2017** [comment]
I test with https://petstore.swagger.io/v2/swagger.json , I got error

```
$ python generator.py swagger.json --output-dir=out --module-name="Title"
Loading specification file...
Using spec format 'json'
not enough values to unpack (expected 2, got 1)

                If you get schema validation errors from a yaml Swagger spec that passes validation on other
                validators, it may be because of single apostrophe's (') used in some descriptions. The
                parser used does not like it at all.

Traceback (most recent call last):
  File "generator.py", line 945, in <module>
    main()
  File "C:\Users\sm2017\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sm2017\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\sm2017\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sm2017\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "generator.py", line 941, in main
    raise e
  File "generator.py", line 929, in main
    generator.load_specification(specification_path, spec_format)
  File "generator.py", line 196, in load_specification
    self._init_class_resources()
  File "generator.py", line 616, in _init_class_resources
    singular, op = operation_id.rsplit("_", 1)
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by DavidOberholzer** [comment]
Hi @sm2017, The format of the `operationId` fields in the swagger spec are required to be in a given format as mentioned in the readme https://github.com/DavidOberholzer/SwaggerReactAdminGenerator#swagger-specification-configuration 

It is difficult to tell what endpoints are what without using a predetermined specification. There is an example specification in the repo `tests/resources/petstore.yml` that can be used to generate an example.

**Comment by cobusc** [comment]
@sm2017 here is another example of a complex spec that works with this tool: https://github.com/girleffect/core-management-portal/blob/develop/swagger/management_layer.yml

**Comment by sm2017** [comment]
Do you support json?

**Comment by cobusc** [comment]
@sm2017 yes. See `--spec-format` command line arg:
```
The specification format (JSON/YAML). Inferred from extension if not given.
```
So if the file has a ".json" extention, it should be parsed correctly. If not, then pass `--spec-format json` explicitly.

**Comment by sm2017** [comment]
What's wrong here https://github.com/DavidOberholzer/SwaggerReactAdminGenerator/issues/5#issuecomment-463547376

**Comment by cobusc** [comment]
@sm2017 the values of the `operationId` fields need to be in snake case form and have the form `<resource>_<action>`. In the spec that you used the values has `camelCase`, which is not supported. The `operationId` value is parsed and thus *must* look like this: `pet_list`, `pet_read`, `pet_update` and `pet_delete`.
It *must not* look like this `petRead`, `petGet`, `myCustomName`

**Comment by cobusc** [comment]
@sm2017 I created https://github.com/DavidOberholzer/SwaggerReactAdminGenerator/issues/6
