### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by kylepott** [DavidOberholzer/SwaggerReactAdminGenerator#8]
Hi there!  I tried a number of attempts on both a YAML and JSON spec for OpenAPI 3.0.0 - I'm wondering has this project been sunset or is there another fork that you could point me to that is working with React Admin >= 3.x and OpenAPI 3.0?

Thanks!

github.com/kylepott

**Comment by DavidOberholzer** [comment]
Hi kylepott, 

It is unfortunately, I'm not able to get time to work on this project at this point and it has not been updated for OpenAPI 3.0.0 or React-Admin newer versions.

All the best with your projects!

**Comment by kylepott** [comment]
Thanks for responding. Best wishes.
